version: "3"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer:arm
    expose:
      - 9000
    ports:
      - 9000:9000
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './portainer/data:/data'
    restart: unless-stopped

  hue-bridge-cc:
    container_name: hue-bridge-cc
    image: ${CC_REGISTRY}/hue-bridge-cc:${CC_HUB_ENVIRONMENT}
    environment:
      - HOST_IP=${CC_HUB_HOST_IP}
    volumes:
      - './hue-bridge-cc/cc-lib:/usr/src/app/cc-lib'
      - './hue-bridge-cc/storage:/usr/src/app/storage'
    restart: unless-stopped

  smart-meter-cc:
    container_name: smart-meter-cc
    image: ${CC_REGISTRY}/smart-meter-cc:${CC_HUB_ENVIRONMENT}
    volumes:
      - './smart-meter-cc/cc-lib:/usr/src/app/cc-lib'
      - './smart-meter-cc/storage:/usr/src/app/storage'
    devices:
      - '/dev/ttyUSB0:/dev/ttyUSB0'
    restart: unless-stopped

  blebox-cc:
    container_name: blebox-cc
    image: ${CC_REGISTRY}/blebox-cc:${CC_HUB_ENVIRONMENT}
    environment:
      - HOST_IP=${CC_HUB_HOST_IP}
    volumes:
      - './blebox-cc/cc-lib:/usr/src/app/cc-lib'
      - './blebox-cc/storage:/usr/src/app/storage'
    restart: unless-stopped

  lifx-cc:
    container_name: lifx-cc
    image: ${CC_REGISTRY}/lifx-cc:${CC_HUB_ENVIRONMENT}
    volumes:
      - './lifx-cc/cc-lib:/usr/src/app/cc-lib'
      - './lifx-cc/storage:/usr/src/app/storage'
    restart: unless-stopped

  dyson-cc:
    container_name: dyson-cc
    image: ${CC_REGISTRY}/dyson-cc:${CC_HUB_ENVIRONMENT}
    environment:
      - HOST_IP=${CC_HUB_HOST_IP}
    volumes:
      - './dyson-cc/cc-lib:/usr/src/app/cc-lib'
      - './dyson-cc/storage:/usr/src/app/storage'
    restart: unless-stopped

  z-way-cc:
    container_name: z-way-cc
    image: ${CC_REGISTRY}/z-way-cc:${CC_HUB_ENVIRONMENT}
    expose:
      - 8083
    ports:
      - 8083:8083
    volumes:
      - z-way-config:/opt/z-way-server/config
      - z-way-automation-storage:/opt/z-way-server/automation/storage
      - z-way-htdocs-smarthome-user:/opt/z-way-server/htdocs/smarthome/user
      - z-way-zddx:/opt/z-way-server/ZDDX
    devices:
      - '/dev/ttyAMA0:/dev/ttyAMA0'
    restart: unless-stopped

volumes:
  z-way-config:
  z-way-automation-storage:
  z-way-htdocs-smarthome-user:
  z-way-zddx:

networks:
  default:
    ipam:
      config:
        - subnet: 10.20.0.0/16
